// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma",
    //    migrations: {
    //        path: "prisma/migrations"
    //    },
    datasource: {
        url: `mysql://${process.env["G_WEB_DATABASE_USER"]}:${process.env["G_WEB_DATABASE_PASSWORD"]}@${process.env["G_WEB_DATABASE_HOST"]}:${process.env["G_WEB_DATABASE_PORT"]}/g_web`  // TODO: I think this won't work on the server
    }
});
