import "server-only";
import fs from "node:fs/promises";
import path from "node:path";
import { NextRequest, NextResponse } from "next/server";
import { C } from "@g/com/lib/config";

// Matches dynmap map names, e.g. "flat" or "iso" (and ensures it is not malicious)
const MAP_NAME_PATTERN = /^[a-zA-Z0-9_-]+$/;

// Matches dynmap tile file names, e.g. "12_-4.jpg" or "zz_12_-4.jpg" for zoomed-out tiles
const TILE_FILE_PATTERN = /^(?:z+_)?(-?\d+)_(-?\d+)\.jpg$/;

const REGION_SIZE = 32;  // Tiles per region edge

/**
 * Dynmap tiles aren't stored in nextjs folders (as they're generated by g_mc), so need to be accessed through a route.
 * This expects the map name to be of the form `[\w-]+`, and the file name to be of the form `[z+_]\d+_\d+.jpg`, and infers the region folder it lives in from the tile's x/y coordinates.
 *
 * Positive x is horizontal from left to right, and positive y is vertical from bottom to top.
 *
 * The coordinates refer to the bottom-left of the top-left unzoomed tile in the given zoomed tile. So if you have a tile called zz_x_y.jpg, that x,y refers to the bottom left of the A in:
 *   ABBB
 *   BBBB
 *   BBBB
 *   BBBB
 */
export async function GET(
    _request: NextRequest,
    { params }: { params: Promise<{ map: string, file: string }> }
) {
    const { map, file } = await params;

    // Validate map name (and ensures it is not malicious)
    if (!MAP_NAME_PATTERN.test(map)) {
        return NextResponse.json({ error: "Invalid map name" }, { status: 400 });
    }

    // Validate and parse filename (and ensures it is not malicious)
    const match = TILE_FILE_PATTERN.exec(file);
    if (match === null) {
        return NextResponse.json({ error: "Invalid tile file name" }, { status: 400 });
    }
    const [, tileXStr, tileYStr] = match;
    const tileX = Number(tileXStr);
    const tileY = Number(tileYStr);

    // We can infer the region from the tile(X,Y)
    const region = `${Math.floor(tileX / REGION_SIZE)}_${Math.floor(tileY / REGION_SIZE)}`;
    const filePath = path.join(C().DYNMAP_TILES_FOLDER, map, region, file);

    // Load data, else return 404
    let data: Buffer;
    try {
        data = await fs.readFile(filePath);
    } catch {
        return NextResponse.json({ error: "Tile not found" }, { status: 404 });
    }

    return new NextResponse(new Uint8Array(data), { headers: { "Content-Type": "image/jpeg" } });
}
