
# Whitelist users 
AllowUsers jon aj
PermitRootLogin no

# Allow only public/private key authentication
PasswordAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
UsePAM no
AuthorizedKeysFile %h/.ssh/authorized_keys

# Non-standard port makes it less likely to be found
Port 31415
