import "server-only";
import fs from "node:fs/promises";
import path from "node:path";
import { NextRequest, NextResponse } from "next/server";

// TODO: Load this from config once the dynmap output location is configurable
const MARKERS_DIR = "/home/greenjon902/Desktop/G-DemMAIN/scripts/g_web/devData/dynmap/_markers_";

// Matches marker icon file names, e.g. "bighouse.png" (and ensures it is not malicious)
const ICON_FILE_PATTERN = /^[a-zA-Z0-9_-]+\.png$/;

/**
 * Marker icons aren't stored in nextjs folders (as they're generated by g_mc), so - like tiles - need
 * to be accessed through a route.
 */
export async function GET(
    _request: NextRequest,
    { params }: { params: Promise<{ icon: string }> }
) {
    const { icon } = await params;

    // Validate filename (and ensures it is not malicious)
    if (!ICON_FILE_PATTERN.test(icon)) {
        return NextResponse.json({ error: "Invalid icon file name" }, { status: 400 });
    }

    // Load data, else return 404
    let data: Buffer;
    try {
        data = await fs.readFile(path.join(MARKERS_DIR, icon));
    } catch {
        return NextResponse.json({ error: "Icon not found" }, { status: 404 });
    }

    return new NextResponse(new Uint8Array(data), { headers: { "Content-Type": "image/png" } });
}
