import "server-only";
import fs from "node:fs/promises";
import path from "node:path";
import { NextRequest, NextResponse } from "next/server";

// TODO: Load this from config once dynmap output location is configurable
const TILES_DIR = "/home/greenjon902/Desktop/G-DemMAIN/scripts/g_web/devData/dynmap/tiles";

// Matches dynmap tile file names, e.g. "12_-4.jpg" or "zz_12_-4.jpg" for zoomed-out tiles
const TILE_FILE_PATTERN = /^(?:z+_)?(-?\d+)_(-?\d+)\.jpg$/;

const REGION_SIZE = 32;  // Tiles per region edge

/**
 * Dynmap tiles aren't stored in nextjs folders (as they're generated by g_mc), so need to be accessed through a route.
 * This expects the file name to be of the form `[z+_]\d+_\d+.jpg`, and infers the region folder it lives in from the tile's x/y coordinates.
 *
 * Positive x is horizontal from left to right, and positive y is vertical from bottom to top.
 */
export async function GET(
    _request: NextRequest,
    { params }: { params: Promise<{ file: string }> }
) {
    const { file } = await params;

    // Validate and parse filename (and ensures it is not malicious)
    const match = TILE_FILE_PATTERN.exec(file);
    if (match === null) {
        return NextResponse.json({ error: "Invalid tile file name" }, { status: 400 });
    }
    const [, tileXStr, tileYStr] = match;
    const tileX = Number(tileXStr);
    const tileY = Number(tileYStr);

    // We can infer the region from the tile(X,Y)
    const region = `${Math.floor(tileX / REGION_SIZE)}_${Math.floor(tileY / REGION_SIZE)}`;
    const filePath = path.join(TILES_DIR, region, file);

    // Load data, else return 404
    let data: Buffer;
    try {
        data = await fs.readFile(filePath);
    } catch {
        return NextResponse.json({ error: "Tile not found" }, { status: 404 });
    }

    return new NextResponse(new Uint8Array(data), { headers: { "Content-Type": "image/jpeg" } });
}
